#!/command/with-contenv bash
#shellcheck shell=bash

if [[ -n "${RTL_TCP}" ]]; then
  exec rtl_tcp -a 0.0.0.0 -p $SRC_PORT -f $FREQ -g $GAIN -s $RATE -d $SERIAL 2>&1 | stdbuf -o0 awk '{print "[rtlmuxer] " strftime("%Y/%m/%d %H:%M:%S", systime()) " " $0}'
else
  exec sleep 86400
fi
